import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import Providers from "@/components/Providers";
import { firaCode, notoSansJP, spaceGrotesk } from "@/lib/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "PySight",
  description: "Generated by create next app",
};

function RootLayout({ children }: Readonly<{children: React.ReactNode;}>) {
  return (
    <html
      lang="ja"
      className={`${notoSansJP.variable} ${spaceGrotesk.variable} ${firaCode.variable}`}
      suppressHydrationWarning
    >
      <body className="bg-(--bg) text-(--fg)">
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}

export default RootLayout;
