import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import { firaCode, notoSansJP, spaceGrotesk } from "@/lib/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "PySight",
  description: "Generated by create next app",
};

function RootLayout({ children }: Readonly<{children: React.ReactNode;}>) {
  return (
    <html
      lang="en"
      className={`${notoSansJP.variable} ${spaceGrotesk.variable} ${firaCode.variable}`}
    >
      <body className="bg-(--bg) text-(--fg)">
        <Navbar />
        {children}
      </body>
    </html>
  );
}

export default RootLayout;
