import type { Metadata } from "next";
import { firaCode, notoSansJP, spaceGrotesk } from "@/lib/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "PySight",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{children: React.ReactNode;}>) {
  return (
    <html
      lang="en"
      className={`${notoSansJP.variable} ${spaceGrotesk.variable} ${firaCode.variable}`}
    >
      <body>
        {children}
      </body>
    </html>
  );
}
